# Generated by Django 4.2.4 on 2023-10-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assurance",
            name="statut",
            field=models.CharField(default="Valide", max_length=50),
        ),
    ]
