# Generated by Django 4.2.4 on 2023-10-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0002_assurance_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employé",
            name="reservations",
            field=models.ManyToManyField(to="flotte_auto.reservationvoiture"),
        ),
    ]
