# Generated by Django 4.2.4 on 2023-10-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0003_alter_employé_reservations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsommationCarburant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "quantite_carburant",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "distance_parcourue",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flotte_auto.vehicule",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DonnéesConsommationCarburant",
        ),
    ]
