# Generated by Django 4.2.4 on 2023-11-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0004_consommationcarburant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employé",
            name="reservations",
        ),
        migrations.AddField(
            model_name="consommationcarburant",
            name="reservation",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to="flotte_auto.reservationvoiture",
            ),
            preserve_default=False,
        ),
    ]
