# Generated by Django 4.2.4 on 2023-11-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0005_remove_employé_reservations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assurance",
            name="compagnie_assurance",
            field=models.CharField(
                choices=[
                    ("Axa", "Axa"),
                    ("NSIA", "NSIA"),
                    ("CNART", "CNART"),
                    ("SenAssurance", "SenAssurance"),
                ],
                max_length=100,
            ),
        ),
    ]
