# Generated by Django 4.2.4 on 2023-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0006_alter_assurance_compagnie_assurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationvoiture",
            name="destination",
            field=models.CharField(
                choices=[
                    ("Dakar", "Dakar"),
                    ("Diourbel", "Diourbel"),
                    ("Fatick", "Fatick"),
                    ("Kaffrine", "Kaffrine"),
                    ("Kaolack", "Kaolack"),
                    ("Kédougou", "Kédougou"),
                    ("Kolda", "Kolda"),
                    ("Louga", "Louga"),
                    ("Matam", "Matam"),
                    ("Saint-Louis", "Saint-Louis"),
                    ("Sédhiou", "Sédhiou"),
                    ("Tambacounda", "Tambacounda"),
                    ("Thiès", "Thiès"),
                    ("Ziguinchor", "Ziguinchor"),
                ],
                max_length=200,
            ),
        ),
    ]
