# Generated by Django 4.2.4 on 2023-11-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0007_alter_reservationvoiture_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assurance",
            name="vehicule",
        ),
        migrations.AddField(
            model_name="vehicule",
            name="assurance",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="flotte_auto.assurance",
            ),
            preserve_default=False,
        ),
    ]
