# Generated by Django 4.2.4 on 2023-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0008_remove_assurance_vehicule_vehicule_assurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="en_cours",
            field=models.BooleanField(default=True),
        ),
    ]
