# Generated by Django 4.2.4 on 2023-11-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0010_remove_consommationcarburant_vehicule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consommationcarburant",
            name="vehicule",
        ),
        migrations.AddField(
            model_name="consommationcarburant",
            name="vehicule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="flotte_auto.vehicule",
            ),
            preserve_default=False,
        ),
    ]
