# Generated by Django 4.2.4 on 2023-11-06 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flotte_auto", "0011_remove_consommationcarburant_vehicule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_signalement", models.DateTimeField(auto_now_add=True)),
                ("date_fin_intervention", models.DateTimeField(blank=True, null=True)),
                (
                    "type_panne",
                    models.CharField(
                        choices=[
                            ("Mécanique", "Mécanique"),
                            ("Electrique", "Electrique"),
                            ("Pneumatique", "Pneumatique"),
                            ("Carrosserie", "Carrosserie"),
                            ("Système de freinage", "Système de freinage"),
                            ("Système de transmission", "Système de transmission"),
                            ("Climatisation", "Climatisation"),
                            (
                                "Système de refroidissement",
                                "Système de refroidissement",
                            ),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=30,
                    ),
                ),
                ("statut", models.CharField(default="En cours", max_length=20)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "conducteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flotte_auto.conducteur",
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flotte_auto.vehicule",
                    ),
                ),
            ],
        ),
    ]
